services:
  nginx-sphynx:
    image: nginx:1.25-alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx/sphynx.conf:/etc/nginx/conf.d/default.conf:ro
      - wordpress-data:/var/www/html
      - ./themes/mm-sphynx:/var/www/html/wp-content/themes/mm-sphynx:delegated
      - nginx-cache:/var/cache/nginx/fastcgi
    depends_on:
      - php-sphynx
    networks:
      - sphynx-net

  php-sphynx:
    build:
      context: ./php
    volumes:
      - wordpress-data:/var/www/html
      - ./themes/mm-sphynx:/var/www/html/wp-content/themes/mm-sphynx:delegated
    environment:
      - PHP_MEMORY_LIMIT=256M
    networks:
      - sphynx-net

  wordpress-sphynx:
    image: wordpress:cli-php8.2
    user: "82:82"
    volumes:
      - wordpress-data:/var/www/html
      - ./scripts:/opt/sphynx-scripts:ro
      - ./content:/opt/sphynx-content:ro
      - ./themes/mm-sphynx:/var/www/html/wp-content/themes/mm-sphynx:delegated
    working_dir: /var/www/html
    entrypoint: ["tail", "-f", "/dev/null"]
    environment:
      WORDPRESS_DB_HOST: mariadb-sphynx:3306
      WORDPRESS_DB_NAME: wp_sphynx
      WORDPRESS_DB_USER: sphynx_user
      WORDPRESS_DB_PASSWORD: sphynx_pass
    depends_on:
      - mariadb-sphynx
      - php-sphynx
    networks:
      - sphynx-net

  mariadb-sphynx:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: root_pass
      MARIADB_DATABASE: wp_sphynx
      MARIADB_USER: sphynx_user
      MARIADB_PASSWORD: sphynx_pass
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - sphynx-net

  redis-sphynx:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - sphynx-net

volumes:
  wordpress-data:
  db-data:
  nginx-cache:

networks:
  sphynx-net:
    driver: bridge
